# Generated by Django 5.2.7 on 2025-10-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='search_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
